<?php
session_start();
if (!isset($_SESSION['user_email']) || $_SESSION['user_role'] !== 'Admin') {
    header('Location: ../auth/login.php?error=unauthorized');
    exit();
}
$adminName = $_SESSION['user_name'] ?? $_SESSION['user_email'];
// PHP logic to read test JSON files from ../data/test_pages/ and display them would go here
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Tests - EduNexus (Static)</title>
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
    <header>
        <h1>Manage Tests</h1>
         <nav class="admin-nav">
            <a href="dashboard.php">Dashboard</a>
            <a href="users.php">Manage Users</a>
            <a href="tests.php">Manage Tests</a>
            <a href="../auth/logout.php">Logout (<?php echo htmlspecialchars($adminName); ?>)</a>
        </nav>
    </header>
    <main style="padding: 2rem;">
        <h2 style="font-size: 1.5rem; margin-bottom: 1rem;">Test Management</h2>
        <p style="margin-bottom: 1.5rem;">Create, view, edit, and manage all test series on the platform.</p>
        
        <a href="#" style="display: inline-block; margin-bottom: 1.5rem; padding: 0.6rem 1.2rem; background-color: #5e35b1; color: white; text-decoration: none; border-radius: 6px;">Create New Test</a>

        <!-- Placeholder for test list table -->
        <table>
            <thead>
                <tr>
                    <th>Test Code</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Subject(s)</th>
                    <th>Total Questions</th>
                    <th>Duration</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="7" style="text-align:center;">Test data will be displayed here.</td>
                </tr>
                <!-- Example Row (dynamically generated by PHP)
                <tr>
                    <td>TEST001</td>
                    <td>Physics Mock 1</td>
                    <td>Full Length</td>
                    <td>Physics</td>
                    <td>50</td>
                    <td>90 mins</td>
                    <td>
                        <a href="#" style="margin-right: 5px; color: #5e35b1;">Edit</a>
                        <a href="#" style="color: #e53935;">Delete</a>
                    </td>
                </tr>
                -->
            </tbody>
        </table>
    </main>
    <footer>
        <p>&copy; <?php echo date("Y"); ?> EduNexus</p>
    </footer>
</body>
</html>
